### ISSUE TITLE
Question regarding admin page vs populate.py script

### ISSUE THREAD

**Issue by drjsoundsgood** [leifos/tango_with_django_book#183]
Hi,
So this isn't an issue but I was wondering if someone could explain this to me.

If I populate the website using the populate.py script, it updates on the admin page.

If I add categories from the admin page, it doesn't get updated on the populate.py script.

Is it better to just work from the populate.py script for adding categories?

**Comment by leifos** [comment]
The idea of having a populations script is so that when you first install
your app you have some test or example data. Sometimes you want to change
the database structure a bit, and it is often easier to delete all
migrations, and rebuild the database, so with the population script you can
regenerate the data. Also, if you working with others they can populate the
database in the same way.

It would be really cool to write a script that exports all your data, to a
new population script though, so that you can later rebuild it.

**Comment by drjsoundsgood** [comment]
thanks for such a quick answer.

that's pretty understandable.
